<?php
/**
 * MmsBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ToastCloud;

/**
 * MmsBodyTest Class Doc Comment
 *
 * @category    Class
 * @description 문자 발송 요청에 필요한 정보들
 * @package     ToastCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MmsBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MmsBody"
     */
    public function testMmsBody()
    {
    }

    /**
     * Test attribute "templateId"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "sendNo"
     */
    public function testPropertySendNo()
    {
    }

    /**
     * Test attribute "requestDate"
     */
    public function testPropertyRequestDate()
    {
    }

    /**
     * Test attribute "sendingGroupingKey"
     */
    public function testPropertySendingGroupingKey()
    {
    }

    /**
     * Test attribute "recipientList"
     */
    public function testPropertyRecipientList()
    {
    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {
    }
}
