<?php
/**
 * RecipientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ToastCloud;

/**
 * RecipientTest Class Doc Comment
 *
 * @category    Class
 * @description 문자 수신자 정보
 * @package     ToastCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecipientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Recipient"
     */
    public function testRecipient()
    {
    }

    /**
     * Test attribute "recipientNo"
     */
    public function testPropertyRecipientNo()
    {
    }

    /**
     * Test attribute "countryCode"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "internationalRecipientNo"
     */
    public function testPropertyInternationalRecipientNo()
    {
    }

    /**
     * Test attribute "templateParameter"
     */
    public function testPropertyTemplateParameter()
    {
    }

    /**
     * Test attribute "recipientGroupingKey"
     */
    public function testPropertyRecipientGroupingKey()
    {
    }
}
