<?php
/**
 * SmsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Toast Cloud SMS
 *
 * Toast Cloud SMS API Specification
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ToastCloud;

use \ToastCloud\Configuration;
use \ToastCloud\ApiException;
use \ToastCloud\ObjectSerializer;

/**
 * SmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ToastCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getSmsSendList
     *
     * 단문 SMS 발송 리스트 조회 (Parameter는 선택적으로 옮겼음).
     *
     */
    public function testGetSmsSendList()
    {
    }

    /**
     * Test case for sendSMS
     *
     * 단문 SMS 발송.
     *
     */
    public function testSendSMS()
    {
    }
}
